# Generated by Django 4.2.4 on 2023-10-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('freshwater_availability', models.FloatField()),
            ],
        ),
    ]
