# Generated by Django 4.2.4 on 2023-10-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterdata',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
